# Generated by Django 5.1.3 on 2024-12-02 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shedule",
            name="class_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.class",
            ),
        ),
        migrations.AddField(
            model_name="shedule",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.subject",
            ),
        ),
        migrations.AddField(
            model_name="shedule",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="shedule",
            name="date_time",
            field=models.DateField(verbose_name="Дата та час проведення"),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.PositiveIntegerField(verbose_name="Оцінка")),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=1,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.subject",
                    ),
                ),
            ],
        ),
    ]
