# Generated by Django 5.1.3 on 2024-12-03 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_shedule_class_group_shedule_subject_shedule_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shedule",
            name="class_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="school.class",
            ),
        ),
        migrations.AlterField(
            model_name="shedule",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="school.subject",
            ),
        ),
        migrations.AlterField(
            model_name="shedule",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="school.teacher",
            ),
        ),
    ]
