# Generated by Django 5.1.3 on 2024-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_alter_shedule_class_group_alter_shedule_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shedule",
            name="date_time",
            field=models.DateTimeField(verbose_name="Дата та час проведення"),
        ),
    ]
