# Generated by Django 5.1.3 on 2024-12-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0009_alter_teacher_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shedule",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.subject",
            ),
        ),
    ]
