# Generated by Django 5.1.3 on 2024-12-04 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0010_alter_shedule_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shedule",
            name="class_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.class",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.class",
            ),
        ),
    ]
