# Generated by Django 5.1.3 on 2024-12-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0011_alter_shedule_class_group_alter_student_class_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shedule",
            name="class_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.class",
            ),
        ),
        migrations.AlterField(
            model_name="shedule",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.subject",
            ),
        ),
    ]
