# Generated by Django 5.1.3 on 2024-12-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0012_alter_shedule_class_group_alter_shedule_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.class",
            ),
        ),
    ]
